name: docker
on: push
jobs:
  node_docker:
    runs-on: ubuntu-latest
    container:
      image: nginx:1.21.4
      ports:
        - 8080:8080
    steps:
      - name: nginx_version
        run: |
          nginx -v
          cat /etc/os-release
