name: first project
on: [push]
jobs:
    run-shell-command:
      runs-on: ubuntu-latest
      steps: 
        - name: echo a string
          run: echo "hello from KG"
        - name: jjjk
          run: |
            node -v
            npm -v
    run-windows-command:
      runs-on: windows-latest
      needs: ["run-shell-command"]
      steps:
        - name: print current directory
          run: pwd
          shell: bash 